### ISSUE TITLE
[Bug]: (Enter a short summary of the bug here）

### ISSUE THREAD

**Issue by Maikidott** [KJHJason/Cultured-Downloader#184]
### Which program are you seeing this problem on?

Cultured Downloader (exe)

### Program Version

4.2.3

### Steps to reproduce the bug

1. Open the executable
2. Set my folder
3. The webdriver instance initializes
4. Then it skips to asking me to "press enter" to quit
5. Doing that makes it say:
Uncaught ValueError
Please provide the developer with the error log generated at
C:\Users\****\AppData\Roaming\Cultured-Downloader\logs\cultured-downloader_v4.2.3_2024-04-10.log

### Expected behaviour

Well this is my first time trying to use it but I was hoping it'd work lol. Opening it again also didn't work either.

### Relevant log output (If any)

----------------------------------------------------------------------------------------------------
2024-04-10 11:52:25,996 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught UnboundLocalError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 148, in get_driver
UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
----------------------------------------------------------------------------------------------------
2024-04-10 11:52:52,236 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/123.0.6312/chromedriver_win32.zip
----------------------------------------------------------------------------------------------------
2024-04-10 11:53:40,625 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/123.0.6312/chromedriver_win32.zip
----------------------------------------------------------------------------------------------------
2024-04-10 11:55:18,141 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/123.0.6312/chromedriver_win32.zip
----------------------------------------------------------------------------------------------------
2024-04-10 11:58:36,154 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/123.0.6312/chromedriver_win32.zip
----------------------------------------------------------------------------------------------------
2024-04-10 12:01:35,923 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/123.0.6312/chromedriver_win32.zip

**Comment by KJHJason** [comment]
Please note that this project's Python program will be the least priority over the development of the new GUI program.

A **_pre-release_** will probably be coming out sooner or later depending on how smoothly the development goes.

**Comment by Maikidott** [comment]
I'm using the .exe version though

**Comment by KJHJason** [comment]
> I'm using the .exe version though

Yes... I do know that.
However, I used [PyInstaller](https://pyinstaller.org/en/stable/) to bundle the Python scripts into an executable for people who are not well-versed in running Python scripts.

**Comment by Maikidott** [comment]
Oh, I understand now, sorry about that. So I just have to wait the new version then?

**Comment by KJHJason** [comment]
Unfortunately... 
However, you can refer to https://github.com/users/KJHJason/projects/2 on how V5.0.0 is coming along.
Alternatively, you can also refer to the [discussions page](https://github.com/KJHJason/Cultured-Downloader/discussions) on updates regarding V5.0.0. 

Otherwise, if you're unable to wait and need to download something, you could use https://github.com/KJHJason/Cultured-Downloader-CLI instead.
