### ISSUE TITLE
[Bug]: Failed to initialise webdriver

### ISSUE THREAD

**Issue by pkr5277** [KJHJason/Cultured-Downloader#49]
### Which program are you seeing this problem on?

Cultured Downloader (py)

### Program Version

4.2.3

### Steps to reproduce the bug

1. run cultured_downloader.py,
2. 
3. 
4.

### Expected behaviour

When I run cultured_downloader.py, I will report such an error, but I have it locally chrome,  and the installation location isC:\Program 
Files\Google\Chrome\Application

### Relevant log output (If any)

Initialising a new webdriver instance...
Failed to initialise a Chrome webdriver instance.
Please check if you have Google Chrome browser installed on your computer.
Google Chrome browser download link: https://www.google.com/chrome/

```
----------------------------------------------------------------------------------------------------
2023-03-28 15:55:56,963 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught UnboundLocalError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 544, in <module>
    main()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 472, in main
    initialise()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 466, in initialise
    with get_driver(download_path=configs.download_directory) as driver:
  File "D:\python program\Cultured-Downloader\src\utils\spinner.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "D:\python program\Cultured-Downloader\src\utils\web_driver.py", line 148, in get_driver
    driver.set_window_size(*window_size)
UnboundLocalError: local variable 'driver' referenced before assignment
```

**Comment by pkr5277** [comment]
----------------------------------------------------------------------------------------------------
2023-03-28 15:26:47,657 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught UnboundLocalError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 544, in <module>
    main()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 472, in main
    initialise()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 466, in initialise
    with get_driver(download_path=configs.download_directory) as driver:
  File "D:\python program\Cultured-Downloader\src\utils\spinner.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "D:\python program\Cultured-Downloader\src\utils\web_driver.py", line 148, in get_driver
    driver.set_window_size(*window_size)
UnboundLocalError: local variable 'driver' referenced before assignment
----------------------------------------------------------------------------------------------------
2023-03-28 15:37:30,423 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught UnboundLocalError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 544, in <module>
    main()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 472, in main
    initialise()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 466, in initialise
    with get_driver(download_path=configs.download_directory) as driver:
  File "D:\python program\Cultured-Downloader\src\utils\spinner.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "D:\python program\Cultured-Downloader\src\utils\web_driver.py", line 148, in get_driver
    driver.set_window_size(*window_size)
UnboundLocalError: local variable 'driver' referenced before assignment
----------------------------------------------------------------------------------------------------
2023-03-28 15:43:26,614 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught WebDriverException
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 544, in <module>
    main()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 472, in main
    initialise()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 466, in initialise
    with get_driver(download_path=configs.download_directory) as driver:
  File "D:\python program\Cultured-Downloader\src\utils\spinner.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "D:\python program\Cultured-Downloader\src\utils\web_driver.py", line 117, in get_driver
    driver_options = webdriver.Chrome(r'D:\python program\Cultured-Downloader\Cultured-Downloader-CLI\webdrivers\chromedriver.exe', options=options)
  File "C:\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 209, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: 

----------------------------------------------------------------------------------------------------
2023-03-28 15:44:50,532 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught UnboundLocalError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 544, in <module>
    main()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 472, in main
    initialise()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 466, in initialise
    with get_driver(download_path=configs.download_directory) as driver:
  File "D:\python program\Cultured-Downloader\src\utils\spinner.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "D:\python program\Cultured-Downloader\src\utils\web_driver.py", line 155, in get_driver
    driver.set_window_size(*window_size)
UnboundLocalError: local variable 'driver' referenced before assignment
----------------------------------------------------------------------------------------------------
2023-03-28 15:55:56,963 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught UnboundLocalError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 544, in <module>
    main()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 472, in main
    initialise()
  File "D:\python program\Cultured-Downloader\src\cultured_downloader.py", line 466, in initialise
    with get_driver(download_path=configs.download_directory) as driver:
  File "D:\python program\Cultured-Downloader\src\utils\spinner.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "D:\python program\Cultured-Downloader\src\utils\web_driver.py", line 148, in get_driver
    driver.set_window_size(*window_size)
UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by KJHJason** [comment]
do you have an anti-virus software running?
