### ISSUE TITLE
[Bug]: Uncaught ValueError

### ISSUE THREAD

**Issue by KeigaTideStar** [KJHJason/Cultured-Downloader#74]
### Which program are you seeing this problem on?

Cultured Downloader (exe)

### Program Version

v4.2.3

### Steps to reproduce the bug

1. Initiate the executable (exe).
2. Answer the download directory question and proceed as usual.
3. You are then prompted to exit instead of loading the full menu.
4. Error code appears after pressing ENTER to quit.

### Expected behaviour

Error Code presented :

Uncaught ValueError
Please provide the developer with the error log generated at
C:\Users\"USERNAME"\AppData\Roaming\Cultured-Downloader\logs\cultured-downloader_v4.2.3_2023-07-26.log
Please press ENTER to shutdown the program...

Could the following text that appears in the logs added below be of help : 

ValueError: There is no such driver by url 
https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip

### Relevant log output (If any)

----------------------------------------------------------------------------------------------------
2023-07-26 13:37:42,659 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip
----------------------------------------------------------------------------------------------------
2023-07-26 13:38:06,734 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip
----------------------------------------------------------------------------------------------------
2023-07-26 13:48:37,571 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip
----------------------------------------------------------------------------------------------------
2023-07-26 13:53:43,279 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip
----------------------------------------------------------------------------------------------------
2023-07-26 13:53:56,908 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip
----------------------------------------------------------------------------------------------------
2023-07-26 15:00:35,490 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught ValueError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "cultured_downloader.py", line 540, in <module>
  File "cultured_downloader.py", line 468, in main
  File "cultured_downloader.py", line 462, in initialise
  File "utils\spinner.py", line 227, in wrapper
  File "utils\web_driver.py", line 110, in get_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip

**Comment by yepyepyepok** [comment]
I have the same issue - can't download anything with this bug.

**Comment by KJHJason** [comment]
Currently, this issue is caused by the [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager) dependency used in Cultured Downloader.

More info: https://github.com/SergeyPirogov/webdriver_manager/issues/580

For now, I would recommend either waiting for a fix on their end or using my [CLI port](https://github.com/KJHJason/Cultured-Downloader-CLI). 
Though, I plan on remaking the main Cultured Downloader with a proper GUI but won't start till mid-August due to examination period and assignment deadlines.

**Comment by Diblox** [comment]
Hey, it seems they fixed it. You may need to update the dependency, if you have time to do so.
