### ISSUE TITLE
[Bug]: Error while starting up webdriver

### ISSUE THREAD

**Issue by yepyepyepok** [KJHJason/Cultured-Downloader#90]
### Which program are you seeing this problem on?

Cultured Downloader (exe), Cultured Downloader (py)

### Program Version

v4.2.3

### Steps to reproduce the bug

1. Launch program from launcher.py, cultured_downloader.py, or the executable file
2. Continue with or without changing path
3. Error occurs: TypeError: ChromeDriverManager.__init__() got an unexpected keyword argument 'path'

### Expected behaviour

The webdriver should have been created without error

### Relevant log output (If any)

2023-09-23 17:01:15,161 [Cultured Downloader V4.2.3] [ERROR]: 
Uncaught TypeError
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\me\Documents\Cultured-Downloader-python-release\src\launcher.py", line 165, in <module>
    cultured_downloader_main()
  File "c:\Users\me\Documents\Cultured-Downloader-python-release\src\cultured_downloader.py", line 468, in main
    initialise()
  File "c:\Users\me\Documents\Cultured-Downloader-python-release\src\cultured_downloader.py", line 462, in initialise
    with get_driver(download_path=configs.download_directory) as driver:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\me\Documents\Cultured-Downloader-python-release\src\utils\spinner.py", line 227, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\me\Documents\Cultured-Downloader-python-release\src\utils\web_driver.py", line 108, in get_driver
    driver_path = ChromeDriverManager(
                  ^^^^^^^^^^^^^^^^^^^^
TypeError: ChromeDriverManager.__init__() got an unexpected keyword argument 'path'

**Comment by yosuahutagalung** [comment]
This could be fixed by removing the arguments `path` and `cache_valid_range` from `src\utils\web_driver.py` line 109-110. Both of those aren't even part of `ChromeDriverManager` constructor parameters.

**Comment by KJHJason** [comment]
> This could be fixed by removing the arguments `path` and `cache_valid_range` from `src\utils\web_driver.py` line 109-110. Both of those aren't even part of `ChromeDriverManager` constructor parameters.

That should be the fix with the latest version of webdriver-manager but I'm currently busy with my internship and also currently starting to focus more on developing the GUI instead of maintaining the python-release branch with the free time I have. 
Thus, I will place this in a backlog until I decide to work on a fix for this issue. 

On the other hand, you can make a pull request to address this issue if you would like, I can merge it into the python-release branch after reviewing.
